sudo: false
language: rust
cache: cargo

# run builds for all the trains (and more)
rust:
  - nightly-2016-04-08
  - beta
  - stable

matrix:
  allow_failures:
    - rust: stable
    - rust: beta

script:
  - cargo build
  - cargo test

notifications:
  email: false
