sudo: required
dist: trusty
language: rust
cache:
  - apt
env:
  global:
    - PATH=$PATH:~/.cargo/bin
addons:
  postgresql: '9.4'

# run builds for all the trains (and more)
rust:
  - nightly
  - beta
  - stable

matrix:
  allow_failures:
    - rust: stable
    - rust: beta

script:
  - cargo install diesel_cli
  - diesel setup
  - diesel migration run
  - cargo build

notifications:
  email: false
