sudo: required
os:
  - linux
  - osx
language: rust
env:
  global:
  - PATH=$PATH:~/.cargo/bin
rust:
- stable
script:
- cd alchemist
- cargo build
- cd ../alchemist_server
- cargo install diesel_cli
- diesel setup
- diesel migration run
- cargo build
notifications:
  email: false
