sudo: required
os:
  - linux
  - osx
language: rust
env:
  global:
  - PATH=$PATH:~/.cargo/bin
rust:
- stable
install: cargo install diesel_cli
script:
    - cd alchemist
    - diesel setup
    - diesel migration run
    - cargo build
    - cd ../alchemist_server
    - diesel setup
    - diesel migration run
    - cargo build
notifications:
  email: false
