[package]
name = "shaper"
version = "0.0.2"
authors = ["Michael Gattozzi <mgattozzi@gmail.com>"]
repository = "https://github.com/mgattozzi/shaper"
homepage = "https://github.com/mgattozzi/shaper"
documentation = "http://mgattozzi.github.io/shaper"
readme = "README.md"
license = "BSD3"

[lib]
name = "shaper"
path = "src/shaper/lib.rs"

[[bin]]
name = "shaper"
path = "src/bin/main.rs"

[dependencies]
clap               = "2.2"
diesel             = "0.6.1"
diesel_codegen     = { version = "0.6.1", default-features = false, features=["nightly", "postgres"] }
dotenv             = "0.8.0"
dotenv_macros      = "0.8.0"
clippy             = "0.0.63"

[profile.dev]
opt-level = 0
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 1

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = false
debug-assertions = false
codegen-units = 1

[profile.test]
opt-level = 0
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 1

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = false
debug-assertions = false
codegen-units = 1

[profile.doc]
opt-level = 0
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 1
