format_strings = true
reorder_imports = true
max_width = 150
report_todo = "Always"
report_fixme = "Always"
comment_width = 100
match_block_trailing_comma = true
space_before_type_annotation = true
space_before_bound = true
use_try_shorthand = true
