CREATE TABLE packages (
    id SERIAL PRIMARY KEY,
    name VARCHAR NOT NULL,
    Arch VARCHAR NOT NULL,
    Ubuntu VARCHAR NOT NULL,
    Mint VARCHAR NOT NULL,
    Debain VARCHAR NOT NULL,
    Gentoo VARCHAR NOT NULL,
    Void VARCHAR NOT NULL,
    Mac VARCHAR NOT NULL,
    FreeBSD VARCHAR NOT NULL,
    NetBSD VARCHAR NOT NULL,
    OpenBSD VARCHAR NOT NULL
)
