(function() {var implementors = {};
implementors['alchemy'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='alchemy/schema/packages/columns/struct.star.html' title='alchemy::schema::packages::columns::star'>star</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='alchemy/schema/packages/columns/struct.id.html' title='alchemy::schema::packages::columns::id'>id</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='alchemy/schema/packages/columns/struct.arch.html' title='alchemy::schema::packages::columns::arch'>arch</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='alchemy/schema/packages/columns/struct.aur.html' title='alchemy::schema::packages::columns::aur'>aur</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='alchemy/schema/packages/columns/struct.ubuntu.html' title='alchemy::schema::packages::columns::ubuntu'>ubuntu</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='alchemy/schema/packages/columns/struct.ubuntu_dev.html' title='alchemy::schema::packages::columns::ubuntu_dev'>ubuntu_dev</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='alchemy/schema/packages/columns/struct.void.html' title='alchemy::schema::packages::columns::void'>void</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='alchemy/schema/packages/struct.table.html' title='alchemy::schema::packages::table'>table</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
